//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Puffix.Utilities.Exceptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class XmlUtilitiesExceptionsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal XmlUtilitiesExceptionsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Puffix.Utilities.Exceptions.XmlUtilitiesExceptionsResources", typeof(XmlUtilitiesExceptionsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while comparing two XML documents..
        /// </summary>
        public static string CompareException {
            get {
                return ResourceManager.GetString("CompareException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while deserializing a XML document or data..
        /// </summary>
        public static string DeserializeException {
            get {
                return ResourceManager.GetString("DeserializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors ({0} errors) were encountered while loading or validating the XML Shema (XSD) set..
        /// </summary>
        public static string LoadingSchemaSetException {
            get {
                return ResourceManager.GetString("LoadingSchemaSetException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object to serialize is not set..
        /// </summary>
        public static string NullObjectToSerializeException {
            get {
                return ResourceManager.GetString("NullObjectToSerializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML data are not set..
        /// </summary>
        public static string NullXmlDataException {
            get {
                return ResourceManager.GetString("NullXmlDataException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The XML document is not set..
        /// </summary>
        public static string NullXmlDocumentException {
            get {
                return ResourceManager.GetString("NullXmlDocumentException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while serializing an object into XML document or data..
        /// </summary>
        public static string SerializeException {
            get {
                return ResourceManager.GetString("SerializeException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors ({0} errors) were encountered while validating a XML document..
        /// </summary>
        public static string XmlValidationException {
            get {
                return ResourceManager.GetString("XmlValidationException", resourceCulture);
            }
        }
    }
}
