name: Build & Publish .NET Package
permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!**.md'
      - '.github/workflows/*.yml'

env:
  DOTNET_VERSION: '10.0.x'
  PACKAGE_VERSION: 10.0.5

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      id: checkout
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Setup .NET Core
      id: setup-dotnet
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}
        
    - name: Install dependencies
      id: dotnet-restore
      run: dotnet restore

    - name: Build
      id: dotnet-build
      run: dotnet build --configuration Release --no-restore

    - name: Test
      id: dotnet-test
      run: dotnet test --no-restore --verbosity normal

    - name: Publish Nuget Package
      id: dotnet-nuget-push
      run: dotnet nuget push /home/runner/work/Puffix.Utilities/Puffix.Utilities/Puffix.Utilities/bin/Release/Puffix.Utilities.${{ env.PACKAGE_VERSION }}.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
